"use client";
import Link from "next/link";
import {useSearchParams} from "next/navigation";
import {Suspense,useMemo,useState} from "react";
import styles from "./Services.module.css";
const services=[
{name:"카카오",slug:"kakao",logo:"/logos/kakao.webp",keywords:["카카오","kakao","카카오톡"],summary:"계정 해지, 데이터 요청, 추모 프로필 안내"},{name:"네이버",slug:"naver",logo:"/logos/naver.svg",keywords:["네이버","naver","블로그","마이박스","mybox"],summary:"회원 탈퇴와 데이터 백업 절차 안내"},{name:"삼성",slug:"samsung",logo:"/logos/samsung.svg",keywords:["삼성","samsung","갤럭시"],summary:"삼성 계정과 기기 데이터 정리 안내"},{name:"구글",slug:"google",logo:"/logos/google.svg",keywords:["구글","google","지메일","gmail","유튜브"],summary:"계정 삭제, 데이터 다운로드, 사후 계정 관리"},{name:"애플",slug:"apple",logo:"/logos/apple.svg",keywords:["애플","apple","아이클라우드","icloud"],summary:"애플 계정과 아이클라우드 데이터 정리 안내"},{name:"메타",slug:"meta",logo:"/logos/meta.svg",keywords:["메타","meta","페이스북"],summary:"페이스북 계정 삭제와 추모 계정 안내"},{name:"인스타그램",slug:"instagram",logo:"/logos/instagram.webp",keywords:["인스타그램","instagram","인스타"],summary:"계정 삭제, 데이터 다운로드, 추모 계정 안내"},{name:"엑스",slug:"x",logo:"/logos/x.svg",keywords:["x","트위터","twitter","엑스"],summary:"계정 비활성화와 삭제 절차 안내"}];
function ServicesDirectory(){const initial=useSearchParams().get("q")||"";const[query,setQuery]=useState(initial);const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return services.filter(s=>!q||s.keywords.some(k=>k.toLowerCase().includes(q)))},[query]);return <main className={styles.page}><div className={styles.wrap}><p className={styles.kicker}>서비스별 안내</p><div className={styles.heading}><div><h1>어떤 서비스를<br/>정리하시나요?</h1><p>회사를 선택하면 가능한 정리 방법과 공식 절차를 확인할 수 있어요.</p></div><label><span>서비스 검색</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="예: 구글, 카카오"/></label></div><div className={styles.list}>{filtered.map(s=><Link href={`/company/${s.slug}`} key={s.slug}><img src={s.logo} alt=""/><span><strong>{s.name}</strong><small>{s.summary}</small></span><em>안내 보기</em></Link>)}{!filtered.length&&<div className={styles.empty}><strong>검색 결과가 없어요.</strong><p>회사명을 다시 확인하거나 전체 목록을 확인해 주세요.</p><button onClick={()=>setQuery("")}>전체 서비스 보기</button></div>}</div></div></main>}
export default function ServicesPage(){return <Suspense fallback={<main className={styles.page}/>}><ServicesDirectory/></Suspense>}
