"use client";
import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import styles from "./Home.module.css";
import {goalsByAudience,isGoalAvailable,shouldShowService,type Audience,type Goal,type Support} from "@/lib/scenario-rules";
const services=[
{name:"카카오",slug:"kakao",logo:"/logos/kakao.webp",keywords:["카카오","kakao","카카오톡"],records:"카카오톡과 카카오 서비스",support:{delete:"지원",download:"조건부 지원",memorial:"지원"}},
{name:"네이버",slug:"naver",logo:"/logos/naver.svg",keywords:["네이버","naver","블로그","mybox"],records:"블로그, 메일, 마이박스",support:{delete:"지원",download:"조건부 지원",memorial:"지원하지 않음"}},
{name:"삼성",slug:"samsung",logo:"/logos/samsung.svg",keywords:["삼성","samsung","갤럭시"],records:"삼성 클라우드, 연락처, 노트",support:{delete:"확인 필요",download:"조건부 지원",memorial:"지원하지 않음"}},
{name:"구글",slug:"google",logo:"/logos/google.svg",keywords:["구글","google","지메일","gmail","유튜브"],records:"구글 포토, 지메일, 드라이브",support:{delete:"지원",download:"조건부 지원",memorial:"지원하지 않음"}},
{name:"애플",slug:"apple",logo:"/logos/apple.svg",keywords:["애플","apple","아이클라우드","icloud"],records:"아이클라우드 사진과 파일",support:{delete:"지원",download:"조건부 지원",memorial:"지원하지 않음"}},
{name:"메타",slug:"meta",logo:"/logos/meta.svg",keywords:["메타","meta","페이스북"],records:"페이스북 게시물, 사진, 메시지",support:{delete:"지원",download:"조건부 지원",memorial:"지원"}},
{name:"인스타그램",slug:"instagram",logo:"/logos/instagram.webp",keywords:["인스타그램","instagram","인스타"],records:"사진, 동영상, 댓글, 계정 정보",support:{delete:"지원",download:"조건부 지원",memorial:"지원"}},
{name:"엑스",slug:"x",logo:"/logos/x.svg",keywords:["x","트위터","twitter","엑스"],records:"게시물, 미디어, 계정 정보",support:{delete:"지원",download:"지원",memorial:"지원하지 않음"}}] as const;
const audiences=[{id:"mine" as const,title:"내 계정을 미리 준비하고 있어요",description:"내 기록을 누구에게 어떻게 남길지 정하고 싶어요."},{id:"deceased" as const,title:"돌아가신 가족의 계정을 정리하고 있어요",description:"계정, 사진과 게시물을 안전하게 정리해야 해요."},{id:"unsure" as const,title:"무엇부터 해야 할지 모르겠어요",description:"세 가지 방법의 차이부터 차근히 안내해 드려요."}];
const goals=[{id:"delete" as const,title:"계정 삭제·해지",description:"계정이나 이용 중인 서비스를 안전하게 종료해요.",icon:"×"},{id:"download" as const,title:"사진·게시물·데이터 다운로드",description:"회사 정책에 따라 기록의 사본을 요청하거나 내려받아요.",icon:"↓"},{id:"memorial" as const,title:"추모 계정 전환",description:"고인의 온라인 공간을 추모 상태로 보존해요.",icon:"○"}];
const unsureResults=[
{id:"download" as const,number:"01",title:"사진과 기록을 먼저 보관하고 싶어요",description:"삭제하기 전에 내려받을 수 있는 데이터를 확인해요."},
{id:"delete" as const,number:"02",title:"계정과 기록을 없애고 싶어요",description:"필요한 기록을 확인한 뒤 계정 삭제 방법을 안내해요."},
{id:"memorial" as const,number:"03",title:"고인의 온라인 공간을 남겨두고 싶어요",description:"추모 계정을 지원하는 회사를 확인해요."},
];
export default function Home(){const router=useRouter();const goalRef=useRef<HTMLElement>(null);const serviceRef=useRef<HTMLElement>(null);const[audience,setAudience]=useState<Audience|null>(null);const[goal,setGoal]=useState<Goal|null>(null);const[showSafeGuide,setShowSafeGuide]=useState(false);const[quickQuery,setQuickQuery]=useState("");const[serviceQuery,setServiceQuery]=useState("");
useEffect(()=>{function restore(event?:PopStateEvent){const params=new URLSearchParams(window.location.hash.slice(1));const hashAudience=params.get("audience");const hashGoal=params.get("goal");if(hashAudience){setAudience(["mine","deceased","unsure"].includes(hashAudience)?hashAudience as Audience:null);setGoal(["delete","download","memorial"].includes(hashGoal??"")?hashGoal as Goal:null);setShowSafeGuide(params.get("guide")==="safe");return}if(event){setAudience(null);setGoal(null);setShowSafeGuide(false);return}const saved=localStorage.getItem("logout-guide-state");if(!saved){setAudience(null);setGoal(null);setShowSafeGuide(false);return}try{const state=JSON.parse(saved);setAudience(["mine","deceased","unsure"].includes(state.audience)?state.audience:null);setGoal(["delete","download","memorial"].includes(state.goal)?state.goal:null);setShowSafeGuide(false)}catch{setAudience(null);setGoal(null);setShowSafeGuide(false)}}restore();window.addEventListener("popstate",restore);return()=>window.removeEventListener("popstate",restore)},[]);
useEffect(()=>{if(audience||goal)localStorage.setItem("logout-guide-state",JSON.stringify({audience,goal}))},[audience,goal]);
useEffect(()=>{if(!isGoalAvailable(audience,goal))setGoal(null)},[audience,goal]);
const filtered=useMemo(()=>{const q=serviceQuery.trim().toLowerCase();return services.filter(s=>!q||s.keywords.some(k=>k.toLowerCase().includes(q)))},[serviceQuery]);
const availableGoals=useMemo(()=>audience?goals.filter(item=>goalsByAudience[audience].includes(item.id)):goals,[audience]);
const ordered=useMemo(()=>{const available=goal?filtered.filter(service=>shouldShowService(goal,service.support[goal] as Support)):filtered;return goal?[...available].sort((a,b)=>rank(a.support[goal] as Support)-rank(b.support[goal] as Support)):available},[filtered,goal]);
function pushHomeState(nextAudience:Audience|null,nextGoal:Goal|null,safe=false){const params=new URLSearchParams();if(nextAudience)params.set("audience",nextAudience);if(nextGoal)params.set("goal",nextGoal);if(safe)params.set("guide","safe");const nextUrl=params.toString()?`#${params.toString()}`:window.location.pathname;window.history.pushState({logoutGuide:{audience:nextAudience,goal:nextGoal,safe}},"",nextUrl)}
function chooseAudience(next:Audience){pushHomeState(next,null);setAudience(next);setGoal(null);setShowSafeGuide(false);setServiceQuery("");setTimeout(()=>goalRef.current?.scrollIntoView({behavior:"smooth",block:"start"}),80)}
function chooseGoal(next:Goal){pushHomeState(audience,next);setGoal(next);setShowSafeGuide(false);setServiceQuery("");setTimeout(()=>serviceRef.current?.scrollIntoView({behavior:"smooth",block:"start"}),80)}
function openSafeGuide(){pushHomeState("unsure",null,true);setShowSafeGuide(true)}
function submit(e:FormEvent){e.preventDefault();const q=quickQuery.trim().toLowerCase();if(!q){router.push("/services");return}const match=services.find(s=>s.keywords.some(k=>k.toLowerCase().includes(q)));if(match)router.push(`/company/${match.slug}`);else router.push(`/services?q=${encodeURIComponent(quickQuery)}`)}
function reset(){setAudience(null);setGoal(null);setShowSafeGuide(false);localStorage.removeItem("logout-guide-state");document.getElementById("start")?.scrollIntoView({behavior:"smooth"})}
return <main className={styles.home}>
<section className={styles.hero}><div className={styles.aurora} aria-hidden="true"/><div className={`container ${styles.heroGrid}`}><div className={styles.heroContent}><p className={styles.kicker}>디지털 유산 안내</p><h1>남겨진 디지털 기록,<br/>차분하게 정리할 수 있도록.</h1><p>계정 삭제부터 데이터 다운로드, 추모 계정 전환까지<br/>회사별 공식 정책과 필요한 절차를 안내합니다.</p><a href="#start" className={styles.heroAction}>안내 시작하기</a></div><div className={styles.lightCanvas} aria-hidden="true"><span className={styles.lightMint}/><span className={styles.lightBlue}/><span className={styles.lightCream}/><span className={styles.lightCore}/><i className={styles.lightRing}/></div></div></section>
<section className={styles.start} id="start"><div className={styles.narrow}><div className={styles.sectionHead}><div><p className={styles.kicker}>안내 시작</p><h2>누구의 디지털 기록인가요?</h2><p>지금 상황을 선택하면 필요한 내용부터 안내해 드려요.</p></div><form className={styles.quickSearch} onSubmit={submit}><label htmlFor="quick-company">회사명으로 바로 찾기</label><div><span>⌕</span><input id="quick-company" value={quickQuery} onChange={e=>setQuickQuery(e.target.value)} placeholder="예: 구글, 카카오"/></div></form></div><div className={styles.choiceList}>{audiences.map(o=><button key={o.id} className={audience===o.id?styles.selected:""} onClick={()=>chooseAudience(o.id)} aria-pressed={audience===o.id}><span className={styles.radio}/><span><strong>{o.title}</strong><small>{o.description}</small></span></button>)}</div><p className={styles.privacyNote}>선택한 진행 상황은 이 기기에만 저장됩니다. 개인정보나 서류는 저장하지 않습니다.</p></div></section>
<section className={`${styles.flowSection} ${!audience?styles.locked:""}`} ref={goalRef} aria-hidden={!audience}><div className={styles.narrow}><Progress step={2}/><button className={styles.back} onClick={()=>window.history.back()}>← 이전 단계</button><p className={styles.kicker}>{audience==="mine"?"내 계정 미리 준비":audience==="deceased"?"고인의 계정 정리":"필요한 도움 찾기"}</p>{audience==="unsure"?<><h2>무엇을 먼저 도와드릴까요?</h2><p className={styles.helper}>지금 정확히 결정하지 않아도 괜찮아요. 원하는 결과와 가장 가까운 항목을 선택해 주세요.</p>{!showSafeGuide?<div className={styles.goalList}>{unsureResults.map(o=><button key={o.id} onClick={()=>chooseGoal(o.id)}><span className={styles.resultNumber}>{o.number}</span><span><strong>{o.title}</strong><small>{o.description}</small></span></button>)}<button onClick={openSafeGuide}><span className={styles.resultNumber}>04</span><span><strong>아직 잘 모르겠어요</strong><small>안전한 순서대로 하나씩 확인해요.</small></span></button></div>:<SafeGuide onStart={()=>chooseGoal("download")} onBack={()=>window.history.back()}/>}</>:<><h2>어떤 도움이 필요하신가요?</h2><div className={styles.goalList}>{availableGoals.map(o=><button key={o.id} onClick={()=>chooseGoal(o.id)} className={goal===o.id?styles.selected:""} aria-pressed={goal===o.id}><span className={styles.goalIcon}>{o.icon}</span><span><strong>{o.title}</strong><small>{o.description}</small></span></button>)}</div></>}</div></section>
<section className={`${styles.services} ${!goal?styles.locked:""}`} id="services" ref={serviceRef} aria-hidden={!goal}><div className={styles.serviceLayout}><aside><Progress step={3}/><button className={styles.back} onClick={()=>window.history.back()}>← 도움 변경</button><p className={styles.kicker}>{goals.find(x=>x.id===goal)?.title}</p><h2>{goal==="download"?"사진과 기록이 있는 서비스를 선택해 주세요":"서비스를 선택해 주세요"}</h2><p>{goal==="memorial"?"추모 계정 전환을 지원하는 서비스만 보여드려요.":goal==="download"?"여러 서비스를 이용한다면 가장 중요한 기록이 있는 곳부터 확인하세요.":"선택한 도움을 제공하는 서비스부터 보여드려요."}</p><label className={styles.serviceSearch}><span>⌕</span><input value={serviceQuery} onChange={e=>setServiceQuery(e.target.value)} placeholder="회사 또는 서비스명 검색"/></label><small className={styles.searchFeedback} aria-live="polite">{serviceQuery.trim()?`${ordered.length}개 서비스를 찾았어요.`:"회사명이나 이용 중인 서비스명을 입력해 보세요."}</small></aside><div className={styles.serviceList}>{ordered.map(s=>{const status=goal?s.support[goal] as Support:"확인 필요";const context=new URLSearchParams();if(audience)context.set("audience",audience);if(goal)context.set("goal",goal);return <Link href={`/company/${s.slug}?${context.toString()}`} key={s.slug} className={styles.serviceRow}><img src={s.logo} alt=""/><span><strong>{s.name}</strong><small>{goal==="download"?s.records:goals.find(x=>x.id===goal)?.title}</small></span><span className={`${styles.status} ${styles[statusClass(status)]}`}>{statusLabel(status)}</span></Link>})}{!ordered.length&&<div className={styles.empty} aria-live="polite"><strong>{goal==="memorial"?"이 서비스는 추모 계정 전환을 지원하지 않아요":"일치하는 서비스가 없어요"}</strong><p>{goal==="memorial"?"다른 회사를 검색하거나 이전 단계에서 다른 도움을 선택해 주세요.":"검색어를 다시 확인하거나 전체 목록에서 선택해 주세요."}</p><button onClick={()=>setServiceQuery("")}>전체 서비스 보기</button></div>}</div></div></section>
{(audience||goal)&&<div className={styles.savedBar}><span>진행 상황이 이 기기에 저장됐어요.</span><button onClick={reset}>진행 기록 삭제</button></div>}</main>}
function Progress({step}:{step:number}){return <div className={styles.progress} aria-label={`4단계 중 ${step}단계`}><span><b>1 상황</b>　—　<b className={step>=2?styles.current:""}>2 목적</b>　—　<b className={step>=3?styles.current:""}>3 서비스</b>　—　4 절차</span><em>{step} / 4</em></div>}
function rank(status:Support){return {"지원":0,"조건부 지원":1,"확인 필요":2,"지원하지 않음":3}[status]}
function statusClass(status:Support){return status==="지원"?"supported":status==="조건부 지원"?"conditional":status==="지원하지 않음"?"unsupported":"checking"}
function statusLabel(status:Support){return status==="지원"?"이용할 수 있어요":status==="조건부 지원"?"일부 기록만 가능해요":status==="지원하지 않음"?"제공하지 않아요":"회사 확인이 필요해요"}

function SafeGuide({onStart,onBack}:{onStart:()=>void;onBack:()=>void}){return <div className={styles.safeGuide}><div className={styles.safeOrder}><p className={styles.kicker}>권장 확인 순서</p><h3>안전한 순서로 확인해 볼게요</h3><ol><li><b>1</b><span>중요한 사진과 기록이 있는지 확인해요.</span></li><li><b>2</b><span>내려받을 수 있는 데이터를 먼저 보관해요.</span></li><li><b>3</b><span>계정을 삭제할지 추모 공간으로 남길지 결정해요.</span></li><li><b>4</b><span>회사를 선택하고 공식 절차를 확인해요.</span></li></ol></div><div className={styles.resultComparison} aria-label="결과별 방법 비교"><div className={styles.comparisonHead}><span>원하는 결과</span><span>적합한 방법</span><span>되돌릴 수 있나요?</span></div><div><span>기록을 보관하고 싶어요</span><strong>데이터 다운로드</strong><span>원본 계정은 유지돼요</span></div><div><span>계정을 없애고 싶어요</span><strong>계정 삭제·해지</strong><span>대부분 되돌리기 어려워요</span></div><div><span>온라인 공간을 남기고 싶어요</span><strong>추모 계정 전환</strong><span>회사 정책에 따라 달라요</span></div></div><div className={styles.safeActions}><button className={styles.secondaryAction} onClick={onBack}>다른 결과 선택하기</button><button className={styles.primaryAction} onClick={onStart}>사진과 기록부터 확인하기</button></div></div>}
