export const companyEnglish: Record<string, { name: string; policyTitle: string; policySubtitle?: string; description: string; button: string; services: string[] }> = {
  apple: { name: "Apple", policyTitle: "Legacy Contact", description: "Apple lets users designate a Legacy Contact in advance. After death, the contact may request access to eligible account data using an access key and a death certificate.", button: "View Apple’s official policy", services: ["iCloud", "Photos", "Notes", "Mail", "iCloud Drive"] },
  google: { name: "Google", policyTitle: "Inactive Account Manager", description: "Google lets users decide who should be contacted, which data may be shared, and whether the account should be deleted after a period of inactivity.", button: "View Google’s official policy", services: ["Gmail", "YouTube", "Google Photos", "Google Drive", "Google Calendar"] },
  meta: { name: "Meta", policyTitle: "Memorialized Account", description: "Facebook can memorialize a deceased person’s profile. A Legacy Contact designated in advance may manage limited parts of the profile.", button: "View Facebook’s official policy", services: ["Facebook", "Messenger"] },
  instagram: { name: "Instagram", policyTitle: "Memorialized Account", description: "Instagram can protect an account in a memorialized state after receiving a valid death report. Immediate family may request removal with supporting documents.", button: "View Instagram’s official policy", services: ["Instagram", "Instagram Direct"] },
  samsung: { name: "Samsung", policyTitle: "Digital Legacy", description: "Samsung lets users designate a Legacy Manager or choose posthumous data deletion. An approved manager can request eligible legacy data with an access code.", button: "View Samsung’s official policy", services: ["Samsung Account", "Samsung Cloud", "Contacts", "Samsung Notes", "Calendar", "Voice Recorder"] },
  naver: { name: "Naver", policyTitle: "Digital Legacy Policy", description: "Naver generally does not transfer private account information to family members. Requests involving public posts or account closure follow a separate review process.", button: "View Naver’s official policy", services: ["Blog", "Cafe", "BAND", "Clip", "Mail", "MYBOX"] },
  kakao: { name: "Kakao", policyTitle: "Digital Legacy Policy", description: "Kakao reviews requests for memorial profiles, account handling, public content, and certain paid balances while protecting private communications.", button: "Visit Kakao Help", services: ["Kakao Account", "KakaoTalk", "KakaoStory", "Daum", "Brunch Story"] },
  x: { name: "X", policyTitle: "Deceased User Account Deactivation", description: "X reviews deactivation requests from verified immediate family members or people authorized to act for the estate. Login information is not provided.", button: "View X’s official policy", services: ["Posts", "Media", "Direct Messages", "Spaces"] },
};
