export type EnglishAction = { id: string; title: string; description: string; guidance: string; link?: string; linkLabel?: string };
type EnglishCompany = { name: string; policyTitle: string; policySubtitle?: string; description: string; button: string; policyLink: string; services: string[]; mine: EnglishAction[]; deceased: EnglishAction[] };

export const companyEnglish: Record<string, EnglishCompany> = {
  apple: { name: "Apple", policyTitle: "Legacy Contact", description: "Apple lets users designate a Legacy Contact in advance. After death, the contact may request access to eligible account data using an access key and a death certificate.", button: "View Apple’s official policy", policyLink: "https://support.apple.com/en-us/102631", services: ["iCloud", "Photos", "Notes", "Mail", "iCloud Drive"],
    mine: [
      { id: "legacy", title: "Add a Legacy Contact", description: "Choose someone who may request access to eligible data after your death.", guidance: "On an Apple device, open Settings or System Settings, select your name, then Sign-In & Security and Legacy Contact. Save and share the generated access key safely.", link: "https://support.apple.com/en-us/102631", linkLabel: "See Apple’s instructions" },
      { id: "download", title: "Download my Apple data", description: "Request a copy of data associated with your Apple Account.", guidance: "Sign in to Apple’s Data and Privacy page, choose Request a copy of your data, select the data and complete the request.", link: "https://privacy.apple.com/", linkLabel: "Open Data and Privacy" },
      { id: "delete", title: "Delete my Apple Account", description: "Permanently delete the account after saving anything you need.", guidance: "Download important files, review subscriptions and signed-in devices, then use Apple’s Data and Privacy page to request deletion.", link: "https://privacy.apple.com/", linkLabel: "Open Data and Privacy" },
    ],
    deceased: [
      { id: "access", title: "I have a Legacy Contact access key", description: "Request access using the access key and death certificate.", guidance: "Prepare the access key and death certificate, then submit them through Apple’s Digital Legacy access request site.", link: "https://digital-legacy.apple.com/", linkLabel: "Request access" },
      { id: "no-key", title: "There is no access key", description: "Review the legal-document route available in your country or region.", guidance: "Apple may require a court order or other legal documentation. Requirements vary by jurisdiction; review Apple’s official guidance before applying.", link: "https://support.apple.com/en-us/102431", linkLabel: "Review Apple’s guidance" },
      { id: "delete", title: "Request account deletion", description: "Ask Apple to delete the deceased person’s account.", guidance: "Contact Apple Support and be ready to provide the death certificate and documents showing your legal authority.", link: "https://support.apple.com/contact", linkLabel: "Contact Apple Support" },
    ] },
  google: { name: "Google", policyTitle: "Inactive Account Manager", description: "Google lets users decide who should be contacted, which data may be shared, and whether the account should be deleted after a period of inactivity.", button: "View Google’s official policy", policyLink: "https://support.google.com/accounts/answer/3036546?hl=en", services: ["Gmail", "YouTube", "Google Photos", "Google Drive", "Google Calendar"],
    mine: [
      { id: "inactive", title: "Set up Inactive Account Manager", description: "Choose contacts, shared data, and whether the account should be deleted.", guidance: "Choose an inactivity period, add trusted contacts, select the data they may receive, and decide whether Google should delete the account.", link: "https://myaccount.google.com/inactive", linkLabel: "Open Inactive Account Manager" },
      { id: "download", title: "Download my Google data", description: "Export data from Google services with Google Takeout.", guidance: "Open Google Takeout, select the services and export format, then download the archive when Google emails you.", link: "https://takeout.google.com/", linkLabel: "Open Google Takeout" },
      { id: "delete", title: "Delete my Google Account", description: "Permanently remove the account and associated data.", guidance: "Back up anything important first, review subscriptions and balances, then follow Google’s account deletion process.", link: "https://support.google.com/accounts/answer/32046?hl=en", linkLabel: "See deletion instructions" },
    ],
    deceased: [
      { id: "data", title: "Request data from the account", description: "Ask Google to review a request for selected account content.", guidance: "Google reviews these requests carefully and does not provide passwords. Prepare proof of death and proof of your relationship or legal authority.", link: "https://support.google.com/accounts/troubleshooter/6357590?hl=en", linkLabel: "Start Google’s request" },
      { id: "close", title: "Close the deceased person’s account", description: "Request permanent closure without receiving login details.", guidance: "Submit Google’s deceased-user request and choose account closure. If you also need data, request it before closing the account.", link: "https://support.google.com/accounts/troubleshooter/6357590?hl=en", linkLabel: "Start Google’s request" },
      { id: "funds", title: "Request funds from the account", description: "Ask Google to review a request involving a remaining balance.", guidance: "Use the deceased-user request form and select the funds option. Google will explain any additional verification needed.", link: "https://support.google.com/accounts/troubleshooter/6357590?hl=en", linkLabel: "Start Google’s request" },
    ] },
  meta: { name: "Meta", policyTitle: "Memorialized Account", description: "Facebook can memorialize a deceased person’s profile. A Legacy Contact designated in advance may manage limited parts of the profile.", button: "View Facebook’s official policy", policyLink: "https://www.facebook.com/help/275013292838654/?locale=en_US", services: ["Facebook", "Messenger"],
    mine: [
      { id: "legacy", title: "Choose a Facebook legacy contact", description: "Designate someone to manage limited parts of a memorialized profile.", guidance: "Open Facebook settings, find Memorialization Settings, choose a legacy contact, and decide whether they may download a copy of shared content.", link: "https://www.facebook.com/help/1070665206293088/?locale=en_US", linkLabel: "See Facebook instructions" },
      { id: "download", title: "Download my Facebook information", description: "Create an archive of information associated with your profile.", guidance: "Use Accounts Center to select the profile, information categories, date range and format for the download.", link: "https://www.facebook.com/help/212802592074644/?locale=en_US", linkLabel: "See download instructions" },
      { id: "delete", title: "Delete my Facebook account", description: "Permanently delete the profile and data you no longer need.", guidance: "Download anything important, then use Accounts Center’s Deactivation or deletion settings.", link: "https://www.facebook.com/help/224562897555674/?locale=en_US", linkLabel: "See deletion instructions" },
    ],
    deceased: [
      { id: "memorialize", title: "Memorialize the account", description: "Ask Facebook to secure the profile as a place for memories.", guidance: "Submit the memorialization request with proof of death such as an obituary or death certificate.", link: "https://www.facebook.com/help/requestmemorialization?locale=en_US", linkLabel: "Request memorialization" },
      { id: "remove", title: "Remove the account", description: "Immediate family may request permanent removal.", guidance: "Prepare proof of death and documents showing that you are an immediate family member or lawful representative.", link: "https://www.facebook.com/help/1518259735093203/?locale=en_US", linkLabel: "Review removal requirements" },
      { id: "manage", title: "Manage as a legacy contact", description: "Manage the limited profile features available to a designated contact.", guidance: "A legacy contact may pin a post, respond to friend requests, and update profile or cover images, but cannot log in as the deceased person.", link: "https://www.facebook.com/help/828408313868251?locale=en_US", linkLabel: "See legacy contact actions" },
    ] },
  instagram: { name: "Instagram", policyTitle: "Memorialized Account", description: "Instagram can protect an account in a memorialized state after receiving a valid death report. Immediate family may request removal with supporting documents.", button: "View Instagram’s official policy", policyLink: "https://www.facebook.com/help/264154560391256/?locale=en_US", services: ["Instagram", "Instagram Direct"],
    mine: [
      { id: "download", title: "Download my Instagram information", description: "Request a copy of photos, comments, profile information, and other eligible data.", guidance: "Use Accounts Center to choose the Instagram profile, information, date range, format and download destination.", link: "https://help.instagram.com/181231772500920?locale=en_US", linkLabel: "See download instructions" },
      { id: "delete", title: "Delete my Instagram account", description: "Permanently remove the account after saving important content.", guidance: "Download anything you need first, then use Accounts Center’s account ownership and control settings to request deletion.", link: "https://help.instagram.com/139886812848894?locale=en_US", linkLabel: "See deletion instructions" },
    ],
    deceased: [
      { id: "memorialize", title: "Memorialize the Instagram account", description: "Submit proof of death so Instagram can secure the account.", guidance: "A valid request may include an obituary or news article. No one is given login access to a memorialized account.", link: "https://www.facebook.com/help/264154560391256/?locale=en_US", linkLabel: "Review the official process" },
      { id: "remove", title: "Request account removal", description: "Verified immediate family may request permanent removal.", guidance: "Prepare the death certificate and proof that you are immediate family or legally authorized to represent the deceased person or estate.", link: "https://www.facebook.com/help/264154560391256/?locale=en_US", linkLabel: "Review removal requirements" },
    ] },
  samsung: { name: "Samsung", policyTitle: "Digital Legacy", description: "Samsung lets users designate a Legacy Manager or choose posthumous data deletion. An approved manager can request eligible legacy data with an access code.", button: "View Samsung’s official policy", policyLink: "https://digital-legacy.samsung.com/", services: ["Samsung Account", "Samsung Cloud", "Contacts", "Samsung Notes", "Calendar", "Voice Recorder"],
    mine: [
      { id: "manager", title: "Designate a Legacy Manager", description: "Choose a person and securely share the generated access code.", guidance: "Open Samsung’s Digital Legacy settings, designate a manager, choose eligible data, and save the access code with your important records.", link: "https://digital-legacy.samsung.com/", linkLabel: "Open Samsung Digital Legacy" },
      { id: "download", title: "Download my Samsung data", description: "Review export options for Samsung Account services.", guidance: "Sign in to Samsung Account privacy settings and check which data-download options are available for the services you use.", link: "https://account.samsung.com/", linkLabel: "Open Samsung Account" },
      { id: "delete", title: "Prepare account deletion", description: "Review data and connected devices before deleting the account.", guidance: "Back up important data, review subscriptions and connected devices, then use Samsung Account settings to delete the account if available.", link: "https://account.samsung.com/", linkLabel: "Open Samsung Account" },
    ],
    deceased: [
      { id: "code", title: "I have the access code", description: "Use the code to request eligible legacy data.", guidance: "Prepare the Legacy Manager access code and death-related documents, then start the request on Samsung’s Digital Legacy site.", link: "https://digital-legacy.samsung.com/", linkLabel: "Start the Samsung process" },
      { id: "no-code", title: "I do not have an access code", description: "Check whether another family or legal request path is available.", guidance: "Samsung’s designated-manager route relies on the access code. Contact Samsung Support to confirm any country-specific alternative and required legal documents.", link: "https://www.samsung.com/us/support/contact/", linkLabel: "Contact Samsung Support" },
    ] },
  naver: { name: "Naver", policyTitle: "Digital Legacy Policy", description: "Naver generally does not transfer private account information to family members. Requests involving public posts or account closure follow a separate review process.", button: "View Naver Help", policyLink: "https://help.naver.com/service/5640/contents/17441?lang=en", services: ["Blog", "Cafe", "BAND", "Clip", "Mail", "MYBOX"],
    mine: [
      { id: "download", title: "Organize or download my data", description: "Review export options inside each Naver service.", guidance: "Back up public posts and files from the relevant service. Availability differs between Blog, Cafe, Mail and MYBOX.", link: "https://help.naver.com/?lang=en", linkLabel: "Open Naver Help" },
      { id: "delete", title: "Close my Naver account", description: "Back up important content before withdrawing from Naver.", guidance: "Check paid services, balances and stored content first, then use Naver account settings to begin withdrawal.", link: "https://help.naver.com/?lang=en", linkLabel: "Open Naver Help" },
    ],
    deceased: [
      { id: "public", title: "Request help with public posts", description: "Ask whether eligible public content can be backed up or handled.", guidance: "Prepare the deceased person’s Naver ID if known, proof of death, and documents showing your family relationship or legal authority.", link: "https://help.naver.com/service/5640/contents/17441?lang=en", linkLabel: "Review Naver’s policy" },
      { id: "close", title: "Request account closure", description: "Ask Naver to review closure of the deceased person’s account.", guidance: "Naver does not provide passwords or private account information. Prepare proof of death and relationship documents for review.", link: "https://help.naver.com/service/5640/contents/17441?lang=en", linkLabel: "Review Naver’s policy" },
      { id: "balance", title: "Ask about a remaining Naver Pay balance", description: "Check the separate process for money or paid balances.", guidance: "Contact Naver Pay support and prepare documents proving death and your authority to handle the estate.", link: "https://help.pay.naver.com/", linkLabel: "Open Naver Pay Help" },
    ] },
  kakao: { name: "Kakao", policyTitle: "Digital Legacy Policy", description: "Kakao reviews requests for memorial profiles, account handling, public content, and certain paid balances while protecting private communications.", button: "Visit Kakao Help", policyLink: "https://cs.kakao.com/?locale=en", services: ["Kakao Account", "KakaoTalk", "KakaoStory", "Daum", "Brunch Story"],
    mine: [
      { id: "download", title: "Organize or download my Kakao data", description: "Review export options for the Kakao services you use.", guidance: "Export eligible content from each service before deleting the account. KakaoTalk chats and service data may have separate backup methods.", link: "https://cs.kakao.com/?locale=en", linkLabel: "Open Kakao Help" },
      { id: "delete", title: "Delete my Kakao Account", description: "Check connected services and balances before withdrawal.", guidance: "Review KakaoTalk, paid services, gifts and connected services, back up anything important, then follow Kakao Account withdrawal instructions.", link: "https://cs.kakao.com/?locale=en", linkLabel: "Open Kakao Help" },
    ],
    deceased: [
      { id: "memorial", title: "Ask about a memorial profile", description: "Check whether a KakaoTalk memorial profile can be requested.", guidance: "Contact Kakao Support and prepare proof of death and family relationship documents. Availability may depend on the service and account status.", link: "https://cs.kakao.com/?locale=en", linkLabel: "Contact Kakao Help" },
      { id: "account", title: "Request help with the account", description: "Ask about public content or account handling without receiving private messages.", guidance: "Kakao protects private communications and does not provide login details. Prepare death and relationship documents for the relevant service.", link: "https://cs.kakao.com/?locale=en", linkLabel: "Contact Kakao Help" },
      { id: "balance", title: "Ask about paid balances or unused gifts", description: "Check whether eligible monetary value can be refunded.", guidance: "Contact the support channel for the relevant paid service and prepare documents showing your authority to handle the estate.", link: "https://cs.kakao.com/?locale=en", linkLabel: "Contact Kakao Help" },
    ] },
  x: { name: "X", policyTitle: "Deceased User Account Deactivation", description: "X reviews deactivation requests from verified immediate family members or people authorized to act for the estate. Login information is not provided.", button: "View X’s official policy", policyLink: "https://help.x.com/en/rules-and-policies/contact-x-about-a-deceased-family-members-account", services: ["Posts", "Media", "Direct Messages", "Spaces"],
    mine: [
      { id: "archive", title: "Download my X data archive", description: "Request an archive containing account information and posts.", guidance: "Open X settings, choose Your account, then Download an archive of your data. Complete identity verification and wait for the download notice.", link: "https://help.x.com/en/managing-your-account/how-to-download-your-x-archive", linkLabel: "See X archive instructions" },
      { id: "delete", title: "Deactivate my X account", description: "Start the deactivation period before permanent deletion.", guidance: "Download anything important first, then deactivate the account in settings. Permanent deletion follows if you do not reactivate during X’s stated period.", link: "https://help.x.com/en/managing-your-account/how-to-deactivate-x-account", linkLabel: "See deactivation instructions" },
    ],
    deceased: [
      { id: "deactivate", title: "Deactivate the deceased person’s account", description: "Submit a request as immediate family or an authorized estate representative.", guidance: "Submit the form first. X will email instructions for providing your ID, the death certificate, and information about the deceased person.", link: "https://help.x.com/en/forms/account-access/deactivate-or-close-account/deactivate-account-for-deceased", linkLabel: "Start X’s request" },
      { id: "media", title: "Report media showing the moment of death", description: "Family or an authorized representative may request review of sensitive media.", guidance: "Prepare the relevant post URLs, death certificate, identification, and proof of your relationship or authority.", link: "https://help.x.com/en/forms/report-moment-of-death", linkLabel: "Open the report form" },
    ] },
};
