import { CompanyPolicy } from "./types";

export const companies: CompanyPolicy[] = [
  {
    id: "apple",
    slug: "apple",
    company: "Apple",
    platform: "Apple Account / iCloud",
    category: "디바이스·클라우드",
    summary: "Legacy Contact를 통한 사전 지정과 법적 문서를 통한 사후 요청 경로를 제공합니다.",
    philosophy: "사망 전 자기결정권과 사전 계획을 우선하는 구조입니다.",
    preDeathPlanning: "yes",
    accountDeletion: "yes",
    memorialAccount: "no",
    dataDownload: "yes",
    familyAccess: "partial",
    courtOrder: "partial",
    requiredDocs: ["사망증명서", "Legacy Contact Access Key 또는 법원 명령 등 법적 문서"],
    available: ["사진", "메모", "메일", "연락처", "캘린더", "메시지", "iCloud Drive", "음성 메모", "Safari 데이터"],
    unavailable: ["구매한 미디어", "구독", "결제 정보", "Keychain"],
    limitations: ["접근 범위는 계정 및 국가별 법적 요건에 따라 달라질 수 있습니다."],
    officialLinks: [{ label: "공식 링크 추가 예정" }],
    lastUpdated: "2026-07-10"
  },
  {
    id: "google",
    slug: "google",
    company: "Google",
    platform: "Google Account",
    category: "포털·클라우드",
    summary: "Inactive Account Manager와 사망자 계정 요청 절차를 운영합니다.",
    philosophy: "사망 자체보다 장기 비활성과 사전 계획을 중심으로 설계되어 있습니다.",
    preDeathPlanning: "yes",
    accountDeletion: "yes",
    memorialAccount: "no",
    dataDownload: "partial",
    familyAccess: "partial",
    courtOrder: "partial",
    requiredDocs: ["사망 확인 문서", "가족 또는 법적 대리 관계를 입증하는 자료"],
    available: ["사전 지정 시 일부 데이터 공유", "사후 요청 검토"],
    unavailable: ["비밀번호 제공"],
    limitations: ["요청이 승인된다고 보장되지 않습니다."],
    officialLinks: [{ label: "공식 링크 추가 예정" }],
    lastUpdated: "2026-07-10"
  },
  {
    id: "facebook",
    slug: "facebook",
    company: "Facebook",
    platform: "Facebook",
    category: "소셜미디어",
    summary: "기념 계정과 Legacy Contact를 지원합니다.",
    philosophy: "계정을 삭제하지 않고 고인의 온라인 흔적을 보존하는 선택지를 제공합니다.",
    preDeathPlanning: "yes",
    accountDeletion: "yes",
    memorialAccount: "yes",
    dataDownload: "partial",
    familyAccess: "partial",
    courtOrder: "unknown",
    requiredDocs: ["사망 사실을 확인할 수 있는 자료"],
    available: ["기념 계정 전환", "제한된 Legacy Contact 관리"],
    unavailable: ["고인 계정으로 로그인", "비공개 메시지 열람"],
    limitations: ["Legacy Contact의 권한은 제한적입니다."],
    officialLinks: [{ label: "공식 링크 추가 예정" }],
    lastUpdated: "2026-07-10"
  },
  {
    id: "instagram",
    slug: "instagram",
    company: "Instagram",
    platform: "Instagram",
    category: "소셜미디어",
    summary: "기념 계정을 지원하지만 Facebook과 정책 범위가 다릅니다.",
    philosophy: "계정 보존과 오용 방지에 초점을 둡니다.",
    preDeathPlanning: "unknown",
    accountDeletion: "yes",
    memorialAccount: "yes",
    dataDownload: "unknown",
    familyAccess: "no",
    courtOrder: "unknown",
    requiredDocs: ["추가 확인 중"],
    available: ["기념 계정 전환"],
    unavailable: ["추가 확인 중"],
    limitations: ["Facebook 정책과 동일하다고 가정하면 안 됩니다."],
    officialLinks: [{ label: "공식 링크 추가 예정" }],
    lastUpdated: "2026-07-10"
  },
  {
    id: "samsung",
    slug: "samsung",
    company: "Samsung",
    platform: "Samsung Account / Cloud",
    category: "디바이스·클라우드",
    summary: "Legacy Manager 지정 후 승인되면 제한된 데이터에 1년간 접근할 수 있습니다.",
    philosophy: "사전 지정과 제한된 범위의 데이터 이전을 결합한 구조입니다.",
    preDeathPlanning: "yes",
    accountDeletion: "unknown",
    memorialAccount: "no",
    dataDownload: "yes",
    familyAccess: "partial",
    courtOrder: "unknown",
    requiredDocs: ["사망 관련 서류", "Legacy Manager 코드"],
    available: ["연락처", "통화 기록", "음성 녹음", "노트", "캘린더", "리마인더"],
    unavailable: ["갤러리", "Samsung Account 자체", "제3자 서비스 데이터"],
    limitations: ["승인 후 접근 기간은 1년입니다."],
    officialLinks: [{ label: "공식 링크 추가 예정" }],
    lastUpdated: "2026-07-10"
  },
  {
    id: "naver",
    slug: "naver",
    company: "NAVER",
    platform: "NAVER Account",
    category: "포털",
    summary: "계정 정보와 비공개 이용 정보는 원칙적으로 이전하지 않으며 공개 게시물 백업을 지원할 수 있습니다.",
    philosophy: "개인 계정의 일신전속성과 개인정보 보호를 강하게 우선합니다.",
    preDeathPlanning: "no",
    accountDeletion: "yes",
    memorialAccount: "no",
    dataDownload: "partial",
    familyAccess: "no",
    courtOrder: "unknown",
    requiredDocs: ["가족관계 증명", "동의 또는 요청 서류"],
    available: ["공개 게시물 백업 요청"],
    unavailable: ["아이디·비밀번호", "메일 등 비공개 이용 정보"],
    limitations: ["신청 UI와 절차 안내가 명확하지 않습니다."],
    officialLinks: [{ label: "공식 링크 추가 예정" }],
    lastUpdated: "2026-07-10"
  },
  {
    id: "kakao",
    slug: "kakao",
    company: "Kakao",
    platform: "Kakao Account / KakaoTalk",
    category: "메신저·포털",
    summary: "비공개 정보는 제공하지 않으며 공개 게시물 백업과 일부 유상 잔액 환불을 지원할 수 있습니다.",
    philosophy: "사생활 보호와 재산적 가치의 구분이 뚜렷합니다.",
    preDeathPlanning: "no",
    accountDeletion: "yes",
    memorialAccount: "yes",
    dataDownload: "partial",
    familyAccess: "no",
    courtOrder: "unknown",
    requiredDocs: ["사망 및 가족 관계를 확인할 수 있는 서류"],
    available: ["공개 게시물 백업", "미사용 모바일 교환권 및 유상 선불 잔액 환불", "카카오톡 추모 프로필"],
    unavailable: ["계정 정보", "카카오톡 대화", "친구 목록"],
    limitations: ["서비스 환경에 따라 백업 제공이 제한될 수 있습니다."],
    officialLinks: [{ label: "공식 링크 추가 예정" }],
    lastUpdated: "2026-07-10"
  }
];
