import { CompanyPolicy } from "./types";

export const companies: CompanyPolicy[] = [
  {
    id: "apple",
    slug: "apple",
    company: "Apple",
    platform: "Apple Account / iCloud",
    category: "디바이스·클라우드",
    summary: "Legacy Contact를 통한 사전 지정과 법적 문서를 통한 사후 요청 경로를 제공합니다.",
    services: ["iCloud", "Photos", "Notes", "Mail", "iCloud Drive"],
    policyTitle: "유산 관리자",
    policySubtitle: "Legacy Contact",
    policyDescription: "Apple은 사용자가 생전에 유산 관리자를 지정하고, 사망 후 접근 키와 사망 증명서를 통해 일부 계정 데이터에 접근하도록 할 수 있습니다.",
    policyLink: "https://support.apple.com/ko-kr/102631",
    policyButton: "Apple 공식 정책 보기",
    philosophy: "사망 전 자기결정권과 사전 계획을 우선하는 구조입니다.",
    preDeathPlanning: "yes",
    accountDeletion: "yes",
    memorialAccount: "no",
    dataDownload: "yes",
    familyAccess: "partial",
    courtOrder: "partial",
    requiredDocs: ["사망증명서", "Legacy Contact Access Key 또는 법원 명령 등 법적 문서"],
    available: ["사진", "메모", "메일", "연락처", "캘린더", "메시지", "iCloud Drive", "음성 메모", "Safari 데이터"],
    unavailable: ["구매한 미디어", "구독", "결제 정보", "Keychain"],
    limitations: ["접근 범위는 계정 및 국가별 법적 요건에 따라 달라질 수 있습니다."],
    officialLinks: [{ label: "공식 링크 추가 예정" }],
    lastUpdated: "2026-07-10"
  },
  {
    id: "google",
    slug: "google",
    company: "Google",
    platform: "Google Account",
    category: "포털·클라우드",
    summary: "Inactive Account Manager와 사망자 계정 요청 절차를 운영합니다.",
    services: ["Gmail", "YouTube", "Google Photos", "Google Drive", "Google Calendar"],
    policyTitle: "휴면 계정 관리자",
    policySubtitle: "Inactive Account Manager",
    policyDescription: "Google은 사용자가 계정을 일정 기간 사용하지 않을 때 연락할 사람, 공유할 데이터와 계정 삭제 여부를 미리 설정할 수 있도록 합니다.",
    policyLink: "https://support.google.com/accounts/answer/3036546?hl=ko",
    policyButton: "Google 공식 정책 보기",
    philosophy: "사망 자체보다 장기 비활성과 사전 계획을 중심으로 설계되어 있습니다.",
    preDeathPlanning: "yes",
    accountDeletion: "yes",
    memorialAccount: "no",
    dataDownload: "yes",
    familyAccess: "partial",
    courtOrder: "partial",
    requiredDocs: ["사망 확인 문서", "가족 또는 법적 대리 관계를 입증하는 자료"],
    available: ["사전 지정 시 일부 데이터 공유", "사후 요청 검토"],
    unavailable: ["비밀번호 제공"],
    limitations: ["요청이 승인된다고 보장되지 않습니다."],
    officialLinks: [{ label: "공식 링크 추가 예정" }],
    lastUpdated: "2026-07-10"
  },
  {
    id: "facebook",
    slug: "facebook",
    company: "Facebook",
    platform: "Facebook",
    category: "소셜미디어",
    summary: "기념 계정과 Legacy Contact를 지원합니다.",
    services: ["Facebook", "Messenger"],
    policyTitle: "추모 계정",
    policySubtitle: "Memorialized Account",
    policyDescription: "Facebook은 사망한 사용자의 프로필을 추모 계정으로 전환하며, 생전에 지정한 유산 관리자가 제한된 범위에서 프로필을 관리할 수 있습니다.",
    policyLink: "https://www.facebook.com/help/103897939701143/",
    policyButton: "Facebook 공식 정책 보기",
    philosophy: "계정을 삭제하지 않고 고인의 온라인 흔적을 보존하는 선택지를 제공합니다.",
    preDeathPlanning: "yes",
    accountDeletion: "yes",
    memorialAccount: "yes",
    dataDownload: "yes",
    familyAccess: "partial",
    courtOrder: "unknown",
    requiredDocs: ["사망 사실을 확인할 수 있는 자료"],
    available: ["기념 계정 전환", "제한된 Legacy Contact 관리"],
    unavailable: ["고인 계정으로 로그인", "비공개 메시지 열람"],
    limitations: ["Legacy Contact의 권한은 제한적입니다."],
    officialLinks: [{ label: "공식 링크 추가 예정" }],
    lastUpdated: "2026-07-10"
  },
  {
    id: "instagram",
    slug: "instagram",
    company: "Instagram",
    platform: "Instagram",
    category: "소셜미디어",
    summary: "기념 계정을 지원하지만 Facebook과 정책 범위가 다릅니다.",
    services: ["Instagram", "Instagram Direct"],
    policyTitle: "추모 계정",
    policySubtitle: "Memorialized Account",
    policyDescription: "Instagram은 유효한 사망 신고를 받으면 계정을 추모 상태로 보호하며, 직계가족은 증빙서류를 제출해 계정 삭제를 요청할 수 있습니다.",
    policyLink: "https://www.facebook.com/help/instagram/264154560391256",
    policyButton: "Instagram 공식 정책 보기",
    philosophy: "계정 보존과 오용 방지에 초점을 둡니다.",
    preDeathPlanning: "unknown",
    accountDeletion: "yes",
    memorialAccount: "yes",
    dataDownload: "yes",
    familyAccess: "no",
    courtOrder: "unknown",
    requiredDocs: ["추가 확인 중"],
    available: ["기념 계정 전환"],
    unavailable: ["추가 확인 중"],
    limitations: ["Facebook 정책과 동일하다고 가정하면 안 됩니다."],
    officialLinks: [{ label: "공식 링크 추가 예정" }],
    lastUpdated: "2026-07-10"
  },
  {
    id: "samsung",
    slug: "samsung",
    company: "Samsung",
    platform: "Samsung Account / Cloud",
    category: "디바이스·클라우드",
    summary: "Legacy Manager 지정 후 승인되면 제한된 데이터에 1년간 접근할 수 있습니다.",
    services: ["Samsung Account", "Samsung Cloud", "연락처", "Samsung Notes", "캘린더", "리마인더", "음성 녹음"],
    policyTitle: "디지털 유산",
    policySubtitle: "Digital Legacy",
    policyDescription: "Samsung은 사용자가 생전에 유산 관리자를 지정하거나 사후 데이터 삭제를 선택하고, 지정된 관리자가 접근 코드로 유산 데이터를 요청하도록 합니다.",
    policyLink: "https://digital-legacy.samsung.com/",
    policyButton: "Samsung 공식 정책 보기",
    philosophy: "사전 지정과 제한된 범위의 데이터 이전을 결합한 구조입니다.",
    preDeathPlanning: "yes",
    accountDeletion: "unknown",
    memorialAccount: "no",
    dataDownload: "yes",
    familyAccess: "partial",
    courtOrder: "unknown",
    requiredDocs: ["사망 관련 서류", "Legacy Manager 코드"],
    available: ["연락처", "통화 기록", "음성 녹음", "노트", "캘린더", "리마인더"],
    unavailable: ["갤러리", "Samsung Account 자체", "제3자 서비스 데이터"],
    limitations: ["승인 후 접근 기간은 1년입니다."],
    officialLinks: [{ label: "공식 링크 추가 예정" }],
    lastUpdated: "2026-07-10"
  },
  {
    id: "naver",
    slug: "naver",
    company: "NAVER",
    platform: "NAVER Account",
    category: "포털",
    summary: "계정 정보와 비공개 이용 정보는 원칙적으로 이전하지 않으며 공개 게시물 백업을 지원할 수 있습니다.",
    services: ["블로그", "카페", "밴드", "클립", "메일", "MYBOX"],
    policyTitle: "디지털 유산 정책",
    policyDescription: "네이버는 고인의 개인정보와 비공개 이용 정보를 가족에게 이전하지 않는 것을 원칙으로 하며, 공개 게시물 백업이나 계정 탈퇴 등은 별도 확인 절차를 거칩니다.",
    policyLink: "https://help.naver.com/service/5640/contents/17441?lang=ko",
    policyButton: "네이버 공식 정책 보기",
    philosophy: "개인 계정의 일신전속성과 개인정보 보호를 강하게 우선합니다.",
    preDeathPlanning: "no",
    accountDeletion: "yes",
    memorialAccount: "no",
    dataDownload: "partial",
    familyAccess: "no",
    courtOrder: "unknown",
    requiredDocs: ["가족관계 증명", "동의 또는 요청 서류"],
    available: ["공개 게시물 백업 요청"],
    unavailable: ["아이디·비밀번호", "메일 등 비공개 이용 정보"],
    limitations: ["신청 UI와 절차 안내가 명확하지 않습니다."],
    officialLinks: [{ label: "공식 링크 추가 예정" }],
    lastUpdated: "2026-07-10"
  },
  {
    id: "kakao",
    slug: "kakao",
    company: "Kakao",
    platform: "Kakao Account / KakaoTalk",
    category: "메신저·포털",
    summary: "비공개 정보는 제공하지 않으며 공개 게시물 백업과 일부 유상 잔액 환불을 지원할 수 있습니다.",
    services: ["카카오계정", "카카오톡", "카카오스토리", "다음", "브런치스토리"],
    policyTitle: "디지털 유산 정책",
    policyDescription: "카카오는 고인의 사생활과 통신 비밀을 보호하면서 추모 프로필, 계정 처리와 일부 재산적 가치에 관한 요청을 서비스별로 검토합니다.",
    policyLink: "https://cs.kakao.com/",
    policyButton: "카카오 고객센터 보기",
    philosophy: "사생활 보호와 재산적 가치의 구분이 뚜렷합니다.",
    preDeathPlanning: "no",
    accountDeletion: "yes",
    memorialAccount: "yes",
    dataDownload: "partial",
    familyAccess: "no",
    courtOrder: "unknown",
    requiredDocs: ["사망 및 가족 관계를 확인할 수 있는 서류"],
    available: ["공개 게시물 백업", "미사용 모바일 교환권 및 유상 선불 잔액 환불", "카카오톡 추모 프로필"],
    unavailable: ["계정 정보", "카카오톡 대화", "친구 목록"],
    limitations: ["서비스 환경에 따라 백업 제공이 제한될 수 있습니다."],
    officialLinks: [{ label: "공식 링크 추가 예정" }],
    lastUpdated: "2026-07-10"
  }
];
